### ISSUE TITLE
Is it possible to support Oneplus One (bacon) device, please?

### ISSUE THREAD

**Issue by hamedsbt** [acroreiser/android_device_lenovo_a6010#3]
Hi, The Oneplus One (bacon) device has some ROMs that are not safe for daily use because the kernel is not compatible with eBPF. Is it possible to provide support for the Oneplus One (bacon) device, please?

Device tree:
https://github.com/LineageOS/android_device_oneplus_bacon

LineageOS 21 xda forum:
https://xdaforums.com/t/rom-14-unofficial-bacon-lineageos-21-for-the-oneplus-one.4655957

Thank you.

**Comment by acroreiser** [comment]
eBPF is not about security. It's about packet filtering and traffic monitoring features.
To obtain eBPF support you need to backport actual eBPF implementation to your kernel.

OP1 has Linux 3.4. You can try to cherry-pick necessary patches from
https://github.com/acroreiser/kernel_samsung_msm8974
From 3429d8148f4c5c9f2ac2da9ebf4054142413e118 to c6fec90d10e1aafba986df8251789e75d52ef17f

But note: this backport is untested, I tested compilation only.
